openapi: 3.0.3
info:
  title: Boilerplate Backend API
  version: 1.0.0
  description: Auto-served Swagger UI. Expand this file to document all endpoints.
servers:
  - url: /api
paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login with credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid credentials
components:
  schemas:
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          example: secret123
    LoginResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Success
        data:
          type: object
          properties:
            token:
              type: string
              description: JWT access token
